/*
 
 Panorado JS - Panoramic Viewer for HTML5
 (c) 2012-2015 by Karl Maloszek - Simple Software
 http://www.panorado.com/en/PanoradoJs.php
 Use is free on private (non-commercial) websites.
 This is not public domain software!
 Comments are welcome.

*/
function PanoradoJS(rb){var Wb,uc,sb,qa,wa,Fa,Ga,tb,ab,bb,A,ub,vc,xa,cb,Ha,Ia,db,T,eb,ga,U,wc,vb,wb,Ja,fb,xb,Ka,Xb,ya,La,Yb,Zb,za,Y,Ma,xc;function yc(a){a&&a.alpha&&!B&&(B=new fd);P&&P.create()}function zc(){var a;a="-- Panoramic Viewer:\n"+("Version: Panorado JS v. "+Wb+"\n");a+="Copyright: "+uc+"\n";a+="Web: "+sb+"\n";a+="License: "+(Na?"commercial ("+Na+")":"private use only")+"\n\n";a=a+"-- Web Browser:\n"+("Name: "+navigator.appName+"\n");a+="Platform: "+navigator.platform+"\n";a+="UserAgent: "+
navigator.userAgent+"\n\n";a+="-- WebGL Graphics:\n";a=Ac()?j?j.ctx?a+("Version: "+j.ctx.getParameter(j.ctx.VERSION)+"\nVendor: "+j.ctx.getParameter(j.ctx.VENDOR)+"\nRenderer: "+j.ctx.getParameter(j.ctx.RENDERER)+"\nShading language version: "+j.ctx.getParameter(j.ctx.SHADING_LANGUAGE_VERSION)+"\nMax. texture size: "+j.ctx.getParameter(j.ctx.MAX_TEXTURE_SIZE)+"\n\n"):a+"Drawing context not available\n\n":a+"Currently not used\n\n":a+"no\n\n";a=a+"-- Device Capabilities:\n"+("Device Pixel Ratio: "+
i+"\nTouch: "+(Z||$?"yes":"no")+(aa?"":" (currently not used)")+"\nOrientation: "+(B?"yes":"no")+(B&&"none"!=B.usrMode?"":" (currently not used)")+"\n\n");a+="-- Video Element Support:\n";var b;if(b=document.createElement("video")){var d;d=""+$b(b,"MP4",'video/mp4; codecs="avc1.42E01E, mp4a.40.2"');d+=$b(b,"WebM",'video/webm; codecs="vp8, vorbis"');b=d+=$b(b,"Ogg Vorbis",'video/ogg; codecs="theora, vorbis"')}else b="none";a=a+b+((I()?"":"(currently not used)\n")+"\n");navigator.getMedia=navigator.getUserMedia||
navigator.webkitGetUserMedia||navigator.mozGetUserMedia;return a=a+"-- User Media Support:\n"+(navigator.getMedia?"yes":"no\n")}function yb(){G();l();setTimeout(function(){/*alert(zc())*/},0)}function $b(a,b,d){var c="no";a.canPlayType&&(c=a.canPlayType(d));c||(c="no");return b+": "+c+"\n"}function V(){return b&&b.video?!0:!1}function I(){return b&&b.video&&b._type==qa?!0:!1}function zb(){return b&&b._type==qa&&b.video&&!b.video.ended&&!b.video.paused?!0:!1}function Ab(){return b&&b._type==Fa?!0:!1}function Ac(){var a=
!1,b=document.createElement("canvas");if(b)try{if(b.getContext("webgl")||b.getContext("experimental-webgl"))a=!0}catch(d){}return a}function ac(){if(I())b.video.currentTime=0,b.video.play();Bc(null)}function bc(){if(b)m=b.pan,s=b.tilt,Bb(),k=Oa(b.scale),W=Q=gb=ha=o=n=0,ia=!1,L=D=0,J=Date.now()}function G(){Aa&&(clearTimeout(Aa),Aa=0);W=ha=o=n=0;L=Date.now();J=0}function w(){return y==Ga}function cc(a){!ba||!ba.length?R=-1:(0>a?a=0:a>ba.length-1&&(a=ba.length-1),R!==a&&(dc(ba[a]),R=a))}function ec(a){cc(R+
a)}function dc(a){y!=tb&&(a?Bc(a):(ja(),fc(null)))}function fc(a){y=ab;if(V())b.video.oncanplay=null,I()&&b.video.pause();b=void 0;if(a){var g=bb,d=null;if(a.type)switch(a.type){case "cubefile":g=Fa;break;case "videofile":g=qa;break;case "livestream":g=wa}if(g!=wa&&!a.src)R=-1,l();else{var c=null;b={};switch(g){case bb:c=Cc(a.src);d="imagefile";break;case Fa:c=Cc(a.src);d="cubefile";break;case qa:var c=a.src,f=a.loop,q=a.autoplay;if(d=document.createElement("video")){d.onerror=ka;d.oncanplay=gd;d.style.display=
"none";d.controls=!1;d.autoplay=!!q;d.loop=!!f;d.preload="auto";for(var c=c.split(";"),q=f=null,u=0;u<c.length;u++){if(c[u].match(/\S.mp4$/i))q="video/mp4";else if(c[u].match(/\S.webm$/i))q="video/webm";else if(c[u].match(/\S.ogg$/i)||c[u].match(/\S.ogv$/i))q="video/ogg";if(q&&d.canPlayType(q)){f=c[u];break}}f?(y=xa,d.src=f,d={video:d,mimeType:q}):(ka(),d=null)}else ka(),d={};if(c=d)a.src=c.video.src;d="videofile";break;case wa:c=hd(),d="livestream"}b._type=g;b.type=d;b.mimeType=c.mimeType;b.img=
c.img;b.video=c.video;b.src=a.src;b.title=a.title?a.title:"";b.description=a.description?a.description:"";b._projection=a.projection&&"spherical"==a.projection?A:ub;z=b._projection;b.projection="spherical"==a.projection?"spherical":"flat";b.horizon=a.horizon?M(Number(a.horizon),-45,45):0;b.pan=a.pan?Number(a.pan):0;b.tilt=a.tilt?Number(a.tilt):0;b.scale="number"==typeof a.scale?Number(a.scale):0;g=Number(a.horzFov);b.horzFov=0<g&&360>g?g:360;b.vertFov=0;b.is360=360==b.horzFov;b.panSpeed=V()?0:vc;
b.tiltSpeed=0;if(null!=a.panSpeed)b.panSpeed=M(Number(a.panSpeed),-ga,ga);if(a.tiltSpeed)b.tiltSpeed=M(Number(a.tiltSpeed),-ga,ga);Pa=a.compassNorth?!0:!1;b.compassNorth=a.compassNorth?Number(a.compassNorth):0;b.compassNorth+=3600;b.compassNorth%=360;b._loop=a.loop&&"true"==a.loop?!0:!1;N=[];ra=null;if(a=a.hotspots)for(g=0;g<a.length;g++)N.push(new id(a[g]));b.hotspots=N;P.create();X()}}else R=-1,l()}function Cc(a){y=xa;var b=new Image,d=null;b.onload=Cb;b.onerror=ka;b.onabort=ka;b.src=a;a.match(/\S.jpg$/i)||
a.match(/\S.jpeg$/i)||a.match(/\S.jfif$/i)?d="image/jpeg":a.match(/\S.png$/i)?d="image/png":a.match(/\S.gif$/i)&&(d="image/gif");return{img:b,mimeType:d}}function gd(a){a=a.target;a.videoWidth&&a.videoHeight?(a.width=a.videoWidth,a.height=a.videoHeight,Cb()):ka()}function Dc(){zb()?b.video.pause():b.video.play()}function Ec(){if(I())return b.video.muted?!1:!0}function hd(){y=xa;var a=document.createElement("video");navigator.getMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia;
if(!navigator.getMedia)return setTimeout(ka,0),a;navigator.getMedia({video:{mandatory:{minWidth:gc}},audio:!1},function(b){a.oncanplay=jd;var d=window.URL||window.webkitURL;a.src=d?d.createObjectURL(b):b;a.play()},function(a){ka();console.log("navigator.getMedia error: "+a.name+" "+a.message)});return{video:a,mimeType:"video/livestream"}}function jd(a){function b(){d.videoWidth&&d.videoHeight?(d.width=d.videoWidth,d.height=d.videoHeight,Cb()):20>c++?setTimeout(b,200):ka()}var d=a.target,c=1;b()}function ka(){y=
cb;ja();l();Qa&&setTimeout(Qa,0)}function Cb(){if(b&&!w()){y=Ga;if(V())b.width=b.video.width,b.height=b.video.height;else if(Ab()){if(!j||b.img.width!=6*b.img.height){y=cb;l();return}b.width=b.img.height*Math.PI;b.height=b.width/2}else b.width=b.img.width,b.height=b.img.height;if(Ab())b.horzFov=360,b.vertFov=180;else if(b.vertFov=b.horzFov*b.height/b.width,180<b.vertFov)b.horzFov*=180/b.vertFov,b.vertFov=180;b.is360=360==b.horzFov;b.scale=Oa(b.scale);b.pan=Ra(b.pan);b.tilt=Sa(b.tilt);Db();bc();X();
Fc=!1;l();Qa&&setTimeout(Qa,0)}}function Bc(a){ja();G();if(b){if(j)j.canvas.style.background="transparent";Eb=!0;Gc();Eb=!1}else if(j&&j.canvas)j.canvas.style.background="#000";if(e.dataUrl){E=new Image;E.onload=function(){if(E&&(E.style.position="absolute",E.style.left=e.canvas.offsetLeft+e.canvas.clientLeft+"px",E.style.top=e.canvas.offsetTop+e.canvas.clientTop+"px",E.width=e.canvas.clientWidth,E.height=e.canvas.clientHeight,E.style.borderRadius=e.getInternalBorderRadiusStyle(),hc=!0,a?fc(a):(bc(),
Fb()),E)){var d=j&&z==A?j.canvas:e.canvas;d.parentNode.insertBefore(E,d);E.style.zIndex=Number(d.style.zIndex)}};try{E.src=e.dataUrl,delete e.dataUrl}catch(g){ja()}}else a?fc(a):(bc(),Fb())}function ja(){Eb=!1;E&&hc&&(E.parentNode&&E.parentNode.removeChild(E),E=void 0,hc=!1);e.dataUrl&&delete e.dataUrl;D=1}function hb(a,b){Hc(m+a,s+b,null)}function Hc(a,b,d){J=0;G();ia=!1;w()&&("number"==typeof d&&(k=Oa(d)),m=a,s=b,l())}function Ba(a){ia=!1;O(k*a)}function O(a){G();w()&&(0!=sa?(gb=k,Q=Oa(a),Q!=k&&
(W=Date.now())):(a=Oa(a),k!=a&&(ic(k,a),k=a)),l())}function Bb(){var a=Ic();la=Math.max(Ha,jc);la=Math.max(la,a);Ca=Math.min(Ia,kc);Ca=Math.max(Ca,la)}function Oa(a){Ta=!1;if("number"!=typeof a||0==a)a=Ic(),Ta=!0;else if(a<la)a=la;else if(a>Ca)a=Ca;else for(var b=[0.125,0.125*Math.SQRT2,0.25,0.25*Math.SQRT2,0.5,0.5*Math.SQRT2,1,1*Math.SQRT2,2,2*Math.SQRT2,4,4*Math.SQRT2,8],d=0;d<b.length;d++)if(a>0.999*b[d]&&a<1.001*b[d]){a=b[d];break}return a}function Ic(){if(!w())return 0;var a=b.width,g=b.height,
d=e.canvas.width,c=e.canvas.height;if(z==A){var f;f=Math.min(b.horzFov,db)/2;d*=f*T/ta(f);f=Math.min(b.vertFov,eb)/2;c*=f*T/ta(f);a=Math.min(a*db/b.horzFov,a);g=Math.min(g*eb/b.vertFov,g)}a=Math.min(d/a,c/g)/i;a=Math.max(a,la);return a=Math.min(a,Ca)}function H(a,b){J=0;var d=n,c=o;G();ia=!1;w()&&(n=null===a?d:M(a,-ga,ga),o=null===b?c:M(b,-ga,ga),L=Date.now(),l())}function Ra(a){if(b.is360)a=(a+36E3)%360;else{var g=Jc()/2,d=b.horzFov-g;g>d?a=b.horzFov/2:a<g?a=g:a>d&&(a=d)}return a}function Sa(a){var g=
Kc(),d=(b.vertFov-g)/2,c=-d,d=d-b.horizon,c=c-b.horizon;z==A&&b.is360&&(90<=b.vertFov/2-b.horizon&&(d+=g/2),90<=b.vertFov/2+b.horizon&&(c-=g/2));d<c?a=(c+d)/2:a<c?a=c:a>d&&(a=d);return a}function ic(a,b){if(ia){var d=Da(a),c=Da(b);m+=d.x-c.x;s+=d.y-c.y}d=k;k=b;m=Ra(m);s=Sa(s);k=d;0==W&&(ia=!1)}function Da(a,g,d,c,f){a||(a=k);if(void 0==g)g=h.x;if(void 0==d)d=h.y;void 0==c&&(c=m);void 0==f&&(f=s);g-=e.canvas.width/2;d=-(d-e.canvas.height/2);if(z==A)var q=b.width/b.horzFov*a*i*U,a=q*S(f)-d*ma(f),f=
q*ma(f)+d*S(f),c=c+Ua(g,a),f=Ua(f,ca(g,a));else c+=g/a/i*b.horzFov/b.width,f+=d/a/i*b.vertFov/b.height;b.is360&&(0>c?c+=360:360<c&&(c-=360));return new Gb(c,f)}function ib(a,g){var d,c;if(z==A){d=b.width/b.horzFov*k*i*U;c=d*S(s)-g*ma(s);var f=d*ma(s)+g*S(s);d=Ua(a,c);c=Ua(f,ca(a,c))}else d=a/k/i*b.horzFov/b.width,c=s+g/k/i*b.vertFov/b.height;b.is360&&(0>d?d+=360:360<d&&(d-=360));return new Gb(d,c)}function Lc(a,g){var d,c;d=a-m;b.is360&&(-180>=d?d+=360:180<d&&(d-=360));if(z==A){var f=b.width/b.horzFov*
k*i*U,q=Ua(ta(g),S(d));c=q-s;if(-90>=c||90<c)return null;var u=f/S(c),q=S(q)*u;d=ta(d)*q;c=ta(c)*f}else c=g-s,d=d/b.horzFov*b.width*k*i,c=c/b.vertFov*b.height*k*i;return new Gb(e.canvas.width/2+d,e.canvas.height/2-c)}function Jc(){var a=e.canvas.width/b.width*b.horzFov/k/i;z==A?(a=2*Math.atan(a*T/2)*U,a=Math.min(a,db)):a=Math.min(a,b.horzFov);return a}function Kc(){if(!e.canvas)return 0;var a=e.canvas.height/b.height*b.vertFov/k/i;z==A?(a=2*Math.atan(a*T/2)*U,a=Math.min(a,eb)):a=Math.min(a,b.vertFov);
return a}function jb(){l(!0)}function l(a){var g=kd();!a||g||b&&b.video&&(b._type==wa||b._type==qa&&!b.video.ended&&!b.video.paused)?(a=10,zb()&&(a=z==A?100:50),setTimeout(function(){Gc();Fb()},a),X()):Fb();g&&Hb&&setTimeout(Hb,0)}function Fb(){if(n||o||J||ha||W||V())wc?ld(jb):(Aa&&(clearTimeout(Aa),Aa=0),Aa=window.setTimeout(jb,10))}function kd(){if(!w())return!1;var a=L,b=m,d=s,c=k;L=Date.now();var f;f=0|md();f|=nd();h.isDragging()&&na?f=!0:(a=(L-a)/1E3,m+=n*a,s+=o*a);var q,u,C,e,a=k;0==W||Q==gb||
(q=1+(L-W)/(500*(2<<sa)),u=Math.log(gb),C=Math.log(Q),e=Math.log(k),u=1+Math.min(2*Math.abs(u-e),Math.abs(C-e)+(C-e)*(C-e))/Math.abs(u-C)/16,q*=u,gb<Q?(a*=q,a>Q&&(a=Q)):(a/=q,a<Q&&(a=Q)),a==Q?(k=a,W=0):W=L);ic(k,a);k=a;f|=b!=m;f|=d!=s;f|=c!=k;return f|=Mc()}function md(){var a=1E3*lc;if(w()){if(0==J)return ja(),!1;if(L<J+a){var g=D;D=(L-J)/a;return D!=g}if(0==b.panSpeed&&0==b.tiltSpeed)return ja(),J=0,!0;if(b.panSpeed!=n||b.tiltSpeed!=o){ja();if(B&&B.mode!=vb)n=o=0;else{a=(L-J-a-2E3)/4E3;if(0>a)return!0;
n=a*b.panSpeed;o=a*b.tiltSpeed;n=0<b.panSpeed?Math.min(b.panSpeed,n):Math.max(b.panSpeed,n);o=0<b.tiltSpeed?Math.min(b.tiltSpeed,o):Math.max(b.tiltSpeed,o)}return!0}ja();J=0;return!1}D=0;return!1}function nd(){if(0==ha||ha==L)return!1;if(ca(n,o)>0.02/k/i*b.horzFov/90){var a=1-(L-ha)/(25*(2<<Ib));if(0<a)return n*=a,o*=a,ha=L,!0}n=o=ha=0;return!0}function Gc(){if(e.ctx&&(y!=xa||Fc)){e.ctx.clearRect(0,0,e.canvas.width,e.canvas.height);Jb()?(j.ctx.clearColor(0,0,0,D),j.ctx.clear(j.ctx.COLOR_BUFFER_BIT)):
(j&&j.ctx&&!E&&(j.ctx.clearColor(0,0,0,1),j.ctx.clear(j.ctx.COLOR_BUFFER_BIT)),e.ctx.globalAlpha=D,e.ctx.fillStyle="#000",e.ctx.fillRect(0,0,e.canvas.width,e.canvas.height));switch(y){case ab:oa("No image selected!");break;case xa:switch(b._type){case bb:case Fa:oa("Loading image\n'"+b.src+"'...");break;case qa:oa("Loading video\n'"+b.src+"'...");break;case wa:oa("Opening live stream...")}break;case cb:switch(b._type){case bb:case Fa:oa("Error loading image file\n'"+b.src+"' !");break;case qa:oa("Error loading video file\n'"+
b.src+"' !");break;case wa:oa("Error opening user media live stream!")}break;case wb:oa("WebGL error: Context lost!");break;case tb:oa("Using Panorado JS viewer from '"+location.hostname+"' requires a valid license key!");break;case Ga:var a=e.canvas.width,g=e.canvas.height,d;e.canvas?(z==A?(d=Math.min(b.horzFov,db),d=2*ta(d/2)/(b.horzFov*T)*b.width*k*i):d=b.width*k*i,d=Math.round(Math.min(d,e.canvas.width))):d=0;var c;z==A?(c=Math.min(b.vertFov,eb),c=2*ta(c/2)/(b.vertFov*T)*b.height*k*i):c=b.height*
k*i;c=Math.round(Math.min(c,e.canvas.height));a=Math.round((a-d)/2);g=Math.round((g-c)/2);d=a+d;c=g+c;z==A?Jb()?(Date.now(),j.paint(a,g,d,c)):(Date.now(),e.paintSpherical(a,g,d,c)):(Date.now(),e.paintFlat(a,g,d,c));Date.now();if(da&&N){e.ctx.save();e.ctx.globalAlpha=D;for(var f=0;f<N.length;f++){var q=N[f];q.paint();!aa&&q.isUnderCursor()&&(ra=q)}e.ctx.restore()}if(!j&&z==A&&y==Ga){f=e.ctx;f.save();f.setTransform(1,0,0,1,0,0);f.globalAlpha=D;f.fillStyle="#000";var q=rb.width,u=rb.height;0<a&&f.fillRect(0,
0,a,u);d<q&&f.fillRect(d,0,d,u);0<g&&f.fillRect(a,0,d-a,g);c<u&&f.fillRect(a,c,d-a,u-c);f.restore()}a=mc();if(!1!==a)g=e.ctx,g.save(),g.drawImage(Nc,a.x,a.y,a.cx,a.cy),g.restore();if(Pa)if(z==A)g=e.canvas.width/2,d=(m-b.compassNorth+3600)%360,Oc(d,g);else{a=50/k*(b.horzFov/b.width);g=[1,2,5,10,15,30,45,90];for(d=0;d<g.length;d++)if(a<=g[d]||d==g.length-1){a=g[d];break}c=m-e.canvas.width/2/k/i*b.horzFov/b.width;c-=b.compassNorth;c=Math.round(c/a)*a;for(c=c-a+b.compassNorth;(g=k*i*b.width/b.horzFov*
(c-m)+e.canvas.width/2)<e.canvas.width;)d=(c-b.compassNorth+36E3)%360,Oc(Math.round(d),g),c+=a}nc&&P.paint();ra&&1==D&&ra.paintPopup()}if(Eb)try{var C=Jb()?j.canvas:e.canvas;e.dataUrl=C.toDataURL("image/png")}catch(Va){e.dataUrl=null}}}function oa(a){var b=e.canvas,d=e.ctx;d.save();d.setTransform(i,0,0,i,0,0);d.globalAlpha=1;var c;c=""+(window.getComputedStyle(b).fontStyle+" ");c+=window.getComputedStyle(b).fontVariant+" ";c+=window.getComputedStyle(b).fontWeight+" ";c+=window.getComputedStyle(b).fontSize+
" ";c+=window.getComputedStyle(b).fontFamily+" ";d.font=c;c=window.getComputedStyle(b).color;"rgb(0, 0, 0)"==c&&(c="#dd0");d.fillStyle=c;d.textBaseline="top";b=parseInt(window.getComputedStyle(b).fontSize);a=a.split("\n");for(c=0;c<a.length;c++)d.fillText(a[c],b,b*(1.3*c+1));d.restore()}function Oc(a,b){var a=Math.round(a),d=od(a),c=0==a%90,f=e.ctx;f.save();f.globalAlpha=D;var q;q=(c?16:12)*i;f.font=q+"px "+Ja;f.textBaseline="bottom";f.lineWidth=1.5*i;f.fillStyle=c?"#ff0":"#fff";f.shadowBlur=6*i;
f.shadowColor="#000";f.beginPath();f.textBaseline="top";f.rect(b,0,1.5*i,12*i);f.stroke();f.fill();f.strokeText(d,b+5*i,1);f.fillText(d,b+5*i,1);f.restore()}function od(a){switch(a){case 0:case 360:return"N";case 90:return"E";case 180:return"S";case 270:return"W";default:return kb(a,3)}}function Mc(){var a=P.mouseOver();if(oc!=a)return oc=a,!0;a=pc();return nc!=a?(nc=a,!0):!1}function pc(){return!ea||!P.visible?!1:(Z||$)&&document.activeElement!=e.canvas?!1:null===h.x?!1:0<=h.x&&h.x<e.canvas.width&&
0<=h.y&&h.y<e.canvas.height}function pd(a){a.imgInfo?(r.imgInfo=new Image,r.imgInfo.onload=function(){l()},r.imgInfo.onerror=function(){r.imgInfo=null},r.imgInfo.src=a.imgInfo):r.imgInfo=Kb(!1);a.imgLink?(r.imgLink=new Image,r.imgLink.onload=function(){l()},r.imgLink.onerror=function(){r.imgLink=null},r.imgLink.src=a.imgLink):r.imgLink=Kb(!0);r.border=!0===a.border;r.shadow=!0===a.shadow;r.opacity="number"==typeof a.opacity?a.opacity:1;r.opacity=M(r.opacity,0,1);if(N)for(a=0;a<N.length;a++)N[a].checkTemplate();
l()}function qc(){if(!da||!N)return null;for(var a=0;a<N.length;a++){var b=N[a];if(b&&b.isUnderCursor())return b}return null}function Kb(a){var b=document.createElement("canvas"),d=b.width=b.height=96,c=b.getContext("2d");c.setTransform(1,0,0,1,48,48);c.beginPath();c.arc(0,0,d/2-2,0,2*Math.PI,!1);c.lineWidth=2;var f=c.createLinearGradient(0,-d/2,0,d/2);f.addColorStop(0,"#f88");f.addColorStop(1,"#a00");c.fillStyle=f;c.stroke();c.fill();c.beginPath();c.arc(0,0,0.4*d,0,2*Math.PI,!1);c.fillStyle="#f00";
c.fill();c.strokeStyle=c.fillStyle="#fff";c.lineCap="round";c.lineJoin="round";c.lineWidth=7;c.shadowBlur=4;c.shadowColor="#444";a?(c.beginPath(),c.moveTo(-15,-15),c.lineTo(15,0),c.lineTo(-15,15)):(c.beginPath(),c.moveTo(-12,-4),c.lineTo(0,-4),c.lineTo(0,20),c.moveTo(-14,20),c.lineTo(14,20),c.stroke(),c.beginPath(),c.arc(-2,-20,2.5,0,2*Math.PI,!1));c.stroke();return b}function mc(){return Na?!1:new lb(e.canvas.width-85,e.canvas.height-30,80,25)}function Pc(a){a?j||(j=new Qc,!j.canvas||!j.ctx?j=void 0:
Db()):j&&!Ab()&&(j.clearBuffers(),j.canvas.parentNode&&j.canvas.parentNode.removeChild(j.canvas),j=null);Lb();l()}function Jb(){return!(!j||!(z==A&&y==Ga))}function Db(){Jb()?j.setBuffers():j&&j.clearBuffers()}function ua(a){if(e.canvas&&a)e.canvas.style.cursor="url("+a+"),move",e.canvas.width=e.canvas.width}function X(){if(e.canvas&&aa)e.canvas.style.cursor="auto";else{var a,b=h.isDragging();if(y==ab||y==cb)a="auto";else if(y==xa)a="wait";else if(ea){var d;if(d=!b)d=(d=mc())?Mb(d):!1;d?a="pointer":
!b&&P.getFunctionUnderCursor()?a="pointer":(a=qc())&&a.isLink()?a="pointer":(a=na?b?Nb:Ob:b?Pb:Qb,a=(a?"url("+a+"),":"")+"move")}else a="auto";e.canvas.style.cursor=a}}function Rc(a){G();e.canvas.removeEventListener("touchstart",Wa,!0);document.removeEventListener("touchend",Xa,!0);document.removeEventListener("touchmove",Ya,!0);e.canvas.removeEventListener("pointerdown",Wa,!0);document.removeEventListener("pointerup",Xa,!0);document.removeEventListener("pointermove",Ya,!0);e.canvas.removeEventListener("mousedown",
Wa,!0);document.removeEventListener("mouseup",Xa,!0);document.removeEventListener("mouseleave",Sc,!0);document.removeEventListener("mousemove",Ya,!0);e.canvas.removeEventListener("mousewheel",Rb,!0);e.canvas.removeEventListener("DOMMouseScroll",Rb,!1);(aa=a&&(Z||$))?Z?(e.canvas.addEventListener("touchstart",Wa,!0),document.addEventListener("touchend",Xa,!0),document.addEventListener("touchmove",Ya,!0)):$&&(e.canvas.addEventListener("pointerdown",Wa,!0),document.addEventListener("pointerup",Xa,!0),
document.addEventListener("pointermove",Ya,!0)):(e.canvas.addEventListener("mousedown",Wa,!0),document.addEventListener("mouseup",Xa,!0),document.addEventListener("mouseleave",Sc,!0),document.addEventListener("mousemove",Ya,!0),e.canvas.addEventListener("mousewheel",Rb,!0),e.canvas.addEventListener("DOMMouseScroll",Rb,!1));l()}function K(a){a.preventDefault();a.stopPropagation()}function mb(a){return window.mozAnimationStartTime?window.mozAnimationStartTime:a.timeStamp}function Mb(a){return!a||h.x<
a.x||h.x>a.x+a.cx||h.y<a.y||h.y>a.y+a.cy?!1:!0}function qd(){}function Tc(){l()}function rd(a){if(ea&&w()&&!h.isDragging()){switch(a.which){case 37:case 177:a.shiftKey?H(n-fb,null):(H(0,0),hb(-1/Math.sqrt(k),0));break;case 39:case 176:a.shiftKey?H(n+fb,null):(H(0,0),hb(1/Math.sqrt(k),0));break;case 38:a.shiftKey?H(null,o+fb):(H(0,0),hb(0,1/Math.sqrt(k)));break;case 40:a.shiftKey?H(null,o-fb):(H(0,0),hb(0,-1/Math.sqrt(k)));break;case 13:nb&&Sb(!0);break;case 27:n||o?H(0,0):nb&&Za&&Sb(!1);break;case 178:H(0,
0);break;case 179:I()?Dc():ac();break;case 107:case 187:case 175:a.ctrlKey||(a.shiftKey?Ba(xb):Ba(Ka));break;case 109:case 189:case 174:a.ctrlKey||(a.shiftKey?Ba(1/xb):Ba(1/Ka));break;case 49:case 97:O(1);break;case 50:case 98:O(2);break;case 53:case 101:O(0.5);break;case 65:O(0);break;case 77:na=!na;X();break;case 67:Pa=!Pa;l();break;case 72:da=!da;l();break;case 73:yb();break;default:return}K(a)}}function Wa(a){ea&&w()&&(a.which&&1!=a.which?h.clear():a.shiftKey||a.ctrlKey||a.altKey?h.clear():a.target!=
e.canvas?h.clear():(h.onEvent(a),K(a),document.activeElement==e.canvas||e.canvas.focus(),rc(),W=J=0,D=1,a=P.getFunctionUnderCursor(),null!==a?(h.clear(),oc=-1,"function"===typeof a&&window.setTimeout(a,0)):(G(),l())))}function Xa(a){3==a.which&&a.target==e.canvas&&window.setTimeout(yb,0);if(ea&&w())if(a.which&&1!=a.which)h.clear();else{var b=h.time,d=h.isPinchZooming();h.onEvent(a);if(d&&!h.isPinchZooming())h.clearPinchZoom();else if(h.isDragging()){K(a);var d=(aa?12:2)*i,c=h.getDragDist()<=d;if(c){var f=
ra,q=f?f.ts:null,u=qc();if(u)u.ts=mb(a);ra=u;if(f||u)if(aa){if(f&&f.isLink()&&(f.isPopupUnderCursor()||f==u&&q+1E3>u.ts)){h.clear();f.gotoUrl();n=o=0;l();return}}else{if(u&&u.isLink()&&u.isUnderCursor()){h.clear();u.gotoUrl();n=o=0;l();return}}else f=mc(),Mb(f)&&(f=self.open(sb,"_blank"))&&f.focus();l()}na&&(b=Math.max((Date.now()-b-100)/-100,0),n*=b,o*=b);0!=Ib&&(0!=n||0!=o)?ha=Date.now():n=o=0;h.time=mb(a);pa&&clearTimeout(pa);if(c&&(ob||pb))pa?(pa=0,pb&&ca(h.x-Uc,h.y-Vc)<d&&setTimeout(pb,0)):(Uc=
h.xDown,Vc=h.yDown,pa=setTimeout(function(){pa=0;ob&&ob()},500));h.clear();X()}else h.clear()}}function Sc(a){a.target==document.body&&window.top!=window.self&&h.isDragging()?(h.clear(),G()):a.target==e.canvas&&(h.onEvent(a),l())}function Ya(a){if(ea&&w())if(a.which&&1!=a.which)h.clear();else{var g=mb(a);if(!Wc||!(g&&g<Date.now()-10)){var d=h.x,c=h.y,g=g-h.time;h.onEvent(a);if(h.isPinchZooming())K(a),rc(),c=h.startScale,d=h.getPinchScale(),c=Da(c,h.xDown,h.yDown),a=Da(d,h.x,h.y),m=h.startPan+c.x-
a.x,s=h.startTilt+c.y-a.y,k=d,m=Ra(m),s=Sa(s),jb();else if(h.isDragging()){K(a);rc();if(pa){clearTimeout(pa);pa=0;return}a=b.horzFov/b.width/k/i;if(na){var f=Da(h.startScale,h.xDown,h.yDown,h.startPan,h.startTilt),q,u=k;q=f.x;var C=f.y,f=h.x-e.canvas.width/2,Va=-(h.y-e.canvas.height/2);if(z==A){var qb=b.width/b.horzFov*u*i*U,u=ca(qb,Va),Va=Ua(Va,qb),v=ca(f,u),qb=ma(C)*v,C=S(C)*v,C=Math.asin(f/C)*U;isNaN(C)&&(C=0<f?90:-90);q-=C;f=Math.acos(qb/u)*U;isNaN(f)&&(f=0<qb?0:180);f=90-f-Va}else q-=f/u/i*b.horzFov/
b.width,f=C-Va/u/i*b.vertFov/b.height;q=new Gb(q,f);m=Ra(q.x);s=Sa(q.y);n/=a;o/=a;n/=2;o/=2;10>g&&(g=10);n+=500*((d-h.x)/g);o-=500*((c-h.y)/g);n*=a;o*=a}else d=h.getDragDistX(),c=h.getDragDistY(),n=d*Math.max(Math.abs(d),100)*Xb*a,o=-c*Math.max(Math.abs(c),100)*Xb*a;jb()}else Mc()?l():aa?X():(d=qc(),d!=ra&&(ra=d,l()));Tb&&setTimeout(Tb,0)}}}function Rb(a){if(ea&&w()&&!sc&&!h.isDragging()&&!a.ctrlKey&&!a.altKey&&!(a.mozInputSource&&a.mozInputSource==a.MOZ_SOURCE_TOUCH)&&!(null!=a.axis&&a.axis==a.HORIZONTAL_AXIS)&&
!(null!=a.wheelDeltaY&&0==a.wheelDeltaY)&&!(null!=a.wheelDelta&&1E4<Math.abs(a.wheelDelta))){var b=a.shiftKey?xb:Ka;e.canvas.focus();h.onEvent(a);var d=0<=(a.detail?-120*a.detail:a.wheelDelta);tc&&(d=!d);var c=0==W?k:Q,b=c*(d?b:1/b);0==sa&&ic(c,b);J=0;G();ia=!0;O(b);K(a)}}function rc(){document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges()}function Xc(a){if(ea&&w()&&B){var g=mb(a);if(!Wc||!(g&&Date.now()-10>g)){B.newEvent(a);var d=B.pan,c=B.tilt;
switch(B.mode){case ya:if(h.isDragging()||h.isPinchZooming())break;d+=b.compassNorth;d%=360;setTimeout(function(){G();m=Ra(d);s=Sa(c);l()},0);break;case La:var c=c+60,d=3<d?d-3:-3>d?d+3:0,c=3<c?c-3:-3>c?c+3:0,f=0.5*d*Math.abs(d),q=0.5*c*Math.abs(c);na&&(f*=-1,q*=-1);J=0;setTimeout(function(){H(f,q)},0)}}}}function Yc(a){if(xc){var b=document.getElementById("debug1");if(b)b.innerHTML="_onCompassNeedsCalibration"}K(a)}function sd(){console.log("Panorado JS: WebGL context lost - trying to restore WebGL!");
y=wb;l();Pc(!0)}function td(){console.log("Panorado JS: WebGL context restored!");Cb()}function Lb(){(i=window.devicePixelRatio)||(i=1);Zc(e.canvas.clientWidth,e.canvas.clientHeight)}function Zc(a,b){ja();e.canvas.width=a*i;e.canvas.height=b*i;if(!e.canvas.style.width||!e.canvas.style.width.match(/%$/))e.canvas.style.width=a+"px";if(!e.canvas.style.height||!e.canvas.style.height.match(/%$/))e.canvas.style.height=b+"px";if(e.canvas&&j&&j.canvas){var d=j.canvas.style;d.zIndex=e.canvas.style.zIndex;
d.position="absolute";d.left=e.canvas.offsetLeft+e.canvas.clientLeft+"px";d.top=e.canvas.offsetTop+e.canvas.clientTop+"px";d.width=a+"px";d.height=b+"px";j.canvas.width=e.canvas.width;j.canvas.height=e.canvas.height;j.canvas.parentNode!=e.canvas.parentNode&&(j.canvas.parentNode.removeChild(j.canvas),e.canvas.parentNode.insertBefore(j.canvas,e.canvas))}d=sa;sa=0;Bb();O(Ta?0:k);sa=d;jb()}function Sb(a){if(e.canvas&&a!=Za){if(j&&j.canvas)j.canvas.style.visibility="hidden";if(Za=a){if(document.body.oldStyleText=
document.body.style.cssText,document.body.style.overflow="hidden",a=e.canvas.style,e.canvas.oldStyleText=e.canvas.style.cssText,a.position="absolute",a.left="0",a.top="0",a.margin="0",a.width="100%",a.height="100%",a.border="none",a.borderRadius="0",a.zIndex=9999,document.documentElement.scrollLeft=0,document.documentElement.scrollTop=0,document.body.scrollLeft=0,document.body.scrollTop=0,document.body.style.width="100%",document.body.style.height="100%",e.canvas.parentNode!=document.body)e.canvas.oldParentNode=
e.canvas.parentNode,e.canvas.placeholder=document.createElement("placeholder"),e.canvas.parentNode.replaceChild(e.canvas.placeholder,e.canvas),document.body.appendChild(e.canvas)}else{if(e.canvas.oldParentNode)e.canvas.parentNode.removeChild(e.canvas),e.canvas.oldParentNode.replaceChild(e.canvas,e.canvas.placeholder),e.canvas.oldParentNode=null,delete e.canvas.placeholder;if(e.canvas.oldStyleText)e.canvas.style.cssText=e.canvas.oldStyleText,delete e.canvas.oldStyleText;document.body.style.overflow=
"";if(document.body.oldStyleText)document.body.style.cssText=document.body.oldStyleText,delete document.body.oldStyleText}Lb()}}function ld(a){(window.requestAnimationFrame||window.webkitRequestAnimationFrame||function(a){window.setTimeout(a,0)})(a)}function kb(a,b){for(var d="",c=Math.pow(10,b-1);a<c&&1<c;)d+="0",c/=10;return d+a}function Qc(){function a(a,b){var f=a.getParameter(a.MAX_TEXTURE_SIZE),f=Math.min(f,8192),e=b.width/b.height,g,v;g=!1;if(b.width>f||b.height>f)g=!0;else if(V())g=!0;else if(0!=
(b.width&b.width-1)||0!=(b.height&b.height-1))g=!0;if(!g)return b.widthUsed=b.width,b.heightUsed=b.height,b;1<=e?(g=Math.min(b.width,f),v=g/e):(v=Math.min(b.height,f),g=v*e);c.width=d(g);c.height=d(v);a=c.getContext("2d");if(!a)return null;for(var e=g/b.width,i=0;i<b.height;i+=f)for(var h=Math.min(f,b.height-i),k=0;k<b.width;k+=f){var j=Math.min(f,b.width-k);try{a.drawImage(b,k,i,j,h,k*e-0,i*e-0,j*e+0,h*e+0)}catch(x){return null}}c.widthUsed=g;c.heightUsed=v;return c}function g(a,b,d){b=a.createShader(b);
a.shaderSource(b,d);a.compileShader(b);return!a.getShaderParameter(b,a.COMPILE_STATUS)?(console.log(a.getShaderInfoLog(b)),y=wb,null):b}function d(a){--a;for(var b=1;32>b;b<<=1)a|=a>>b;return a+1}this.ctx=this.canvas=null;var c=document.createElement("canvas");this.shAlpha=this.shMVMatrix=this.shTextureCoord=this.shVertexPos=this.shaderProg=null;this.numVertices=0;this.mvMatrix=this.texture=null;this.initShaders=function(){var a=this.ctx,b=g(a,a.VERTEX_SHADER,"attribute vec3 aVertexPos;\nattribute vec2 aTextureCoord;\nuniform mat4 uMvMatrix;\nvarying vec2 vTextureCoord;\nvoid main(void) {\ngl_Position = uMvMatrix * vec4(aVertexPos, 1.0);\nvTextureCoord = aTextureCoord;\n}"),
d=g(a,a.FRAGMENT_SHADER,"precision lowp float;\nvarying vec2 vTextureCoord;\nuniform sampler2D uSampler;\nuniform float uAlpha;\nvoid main(void) {\nvec4 textureColor = texture2D(uSampler, vTextureCoord);\ngl_FragColor = vec4(textureColor.rgb, uAlpha);\n}");this.shaderProg=a.createProgram();a.attachShader(this.shaderProg,b);a.attachShader(this.shaderProg,d);a.linkProgram(this.shaderProg);a.getProgramParameter(this.shaderProg,a.LINK_STATUS)?(a.validateProgram(this.shaderProg),a.getProgramParameter(this.shaderProg,
a.VALIDATE_STATUS)?(this.shMVMatrix=a.getUniformLocation(this.shaderProg,"uMvMatrix"),this.shAlpha=a.getUniformLocation(this.shaderProg,"uAlpha"),this.shVertexPos=a.getAttribLocation(this.shaderProg,"aVertexPos"),a.enableVertexAttribArray(this.shVertexPos),this.shTextureCoord=a.getAttribLocation(this.shaderProg,"aTextureCoord"),a.enableVertexAttribArray(this.shTextureCoord),a.useProgram(this.shaderProg)):console.log(a.getShaderInfoLog(this.shaderProg))):console.log(a.getShaderInfoLog(this.shaderProg))};
if(this.canvas=document.createElement("canvas")){try{this.ctx=this.canvas.getContext("webgl")||this.canvas.getContext("experimental-webgl")}catch(f){}this.ctx?(this.canvas.addEventListener("webglcontextlost",sd,!1),this.canvas.addEventListener("webglcontextrestored",td,!1),this.canvas.style.background="transparent",this.canvas.style.border="none",this.canvas.style.borderRadius=e.getInternalBorderRadiusStyle(),e.canvas.parentNode.insertBefore(this.canvas,e.canvas),this.initShaders(),this.ctx.blendFunc(this.ctx.SRC_ALPHA,
this.ctx.ONE_MINUS_SRC_ALPHA),this.ctx.enable(this.ctx.BLEND),this.clearBuffers=function(){var a=this.ctx;a&&a.bindTexture(a.TEXTURE_2D,null);delete this.texture},this.setBuffers=function(){Ab()?this.setCubeBuffers():this.setSphereBuffers()},this.setSphereBuffers=function(){var d=V()?b.video:b.img,c=this.ctx;delete this.texture;if(d=a(c,d)){var f=1/b.horzFov*d.widthUsed/d.width,e=1/b.vertFov*d.heightUsed/d.height,g=d.width!=d.widthUsed,v=[],i=0,h=0,k=0,j=0,x=b.horzFov,k=Math.max(-b.vertFov/2-b.horizon,
-90),l=Math.min(b.vertFov/2-b.horizon,90),t,va,Vb=Ub;85<=b.vertFov/2+Math.abs(b.horizon)||(Vb*=2);for(h=k,k=0,va=!1;!va;h+=Vb,k++){h>=l&&(h=l,va=!0);var F=ma(h),n=S(h),p=(l-h)*e;for(i=0,j=0,t=!1;!t;i+=Vb,j++){i>=x&&(i=x,t=!0);var o=ma(i),s=S(i),m=i*f;t&&g&&b.is360&&(m-=5.0E-4);v.push(new ud(m,p,o*n,F,-s*n))}}f=[];e=[];g=null;for(x=this.numVertices=0;x<k-1;x++){g=v[x*j];f.push(g.x);f.push(g.y);f.push(g.z);e.push(0);e.push(0);this.numVertices++;for(l=0;l<j;l++)g=v[x*j+l],f.push(g.x),f.push(g.y),f.push(g.z),
e.push(g.xSrc),e.push(g.ySrc),g=v[(x+1)*j+l],f.push(g.x),f.push(g.y),f.push(g.z),e.push(g.xSrc),e.push(g.ySrc),this.numVertices+=2;f.push(g.x);f.push(g.y);f.push(g.z);e.push(0);e.push(0);this.numVertices++}c.bindBuffer(c.ARRAY_BUFFER,c.createBuffer());c.bufferData(c.ARRAY_BUFFER,new Float32Array(f),c.STATIC_DRAW);c.vertexAttribPointer(this.shVertexPos,3,c.FLOAT,!1,0,0);c.bindBuffer(c.ARRAY_BUFFER,c.createBuffer());c.bufferData(c.ARRAY_BUFFER,new Float32Array(e),c.STATIC_DRAW);c.vertexAttribPointer(this.shTextureCoord,
2,c.FLOAT,!1,0,0);this.texture=c.createTexture();c.bindTexture(c.TEXTURE_2D,this.texture);try{c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,d),d.width=d.height=0}catch(r){c.bindTexture(c.TEXTURE_2D,null);return}c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,c.LINEAR);if(0.5>=la&&!(85<=b.vertFov/2+Math.abs(b.horizon))&&!V())try{c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR_MIPMAP_NEAREST),c.generateMipmap(c.TEXTURE_2D)}catch(w){c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,
c.LINEAR)}else c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_S,c.CLAMP_TO_EDGE);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_T,c.CLAMP_TO_EDGE)}else y=Yb},this.setCubeBuffers=function(){var c=V()?b.video:b.img,d=this.ctx;delete this.texture;if(c=a(d,c)){var f=c.widthUsed/c.width/6,g=c.heightUsed/c.height,e=1/c.width,i=0.8/c.height,f=[0,0,0,g-i,1*f,0,1*f,g-i,2*f,0,2*f,g-i,3*f,0,3*f,g-i,4*f-e,0,4*f-e,g-i,4*f-e,g-i,4*f+e,0,4*f+e,0,4*f+e,g-i,5*
f-e,0,5*f-e,g-i,5*f-e,g-i,5*f+e,0,5*f+e,0,5*f+e,g-i,6*f-e,0,6*f-e,g-i];this.numVertices=22;d.bindBuffer(d.ARRAY_BUFFER,d.createBuffer());d.bufferData(d.ARRAY_BUFFER,new Float32Array([-1,1,-1,-1,-1,-1,1,1,-1,1,-1,-1,1,1,1,1,-1,1,-1,1,1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,1,1,-1,1,-1,1,1,1,1,1,-1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,-1,1,-1,1]),d.STATIC_DRAW);d.vertexAttribPointer(this.shVertexPos,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ARRAY_BUFFER,d.createBuffer());d.bufferData(d.ARRAY_BUFFER,new Float32Array(f),
d.STATIC_DRAW);d.vertexAttribPointer(this.shTextureCoord,2,d.FLOAT,!1,0,0);this.texture=d.createTexture();d.bindTexture(d.TEXTURE_2D,this.texture);try{d.texImage2D(d.TEXTURE_2D,0,d.RGBA,d.RGBA,d.UNSIGNED_BYTE,c)}catch(h){d.bindTexture(d.TEXTURE_2D,null);return}d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,d.LINEAR);try{d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR_MIPMAP_NEAREST),d.generateMipmap(d.TEXTURE_2D)}catch(k){d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR)}d.texParameteri(d.TEXTURE_2D,
d.TEXTURE_WRAP_S,d.CLAMP_TO_EDGE);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_T,d.CLAMP_TO_EDGE)}else y=Yb},this.paint=function(d,c,f,g){this.canvas.style.visibility="visible";var e=this.ctx;if(!e.isContextLost()){if(V()){var i=a(e,b.video);e.bindTexture(e.TEXTURE_2D,this.texture);e.texImage2D(e.TEXTURE_2D,0,e.RGBA,e.RGBA,e.UNSIGNED_BYTE,i)}f-=d;g-=c;this.ctx.viewport(d,c,f,g);this.setMvMatrix(f,g);e.uniformMatrix4fv(this.shMVMatrix,!1,this.mvMatrix);e.uniform1f(this.shAlpha,D);e.drawArrays(e.TRIANGLE_STRIP,
0,this.numVertices);j.ctx.flush();j.ctx.finish()}},this.setMvMatrix=function(a,d){var c,f=ca(a/b.width*b.horzFov/k/i,d/b.height*b.vertFov/k/i);c=2*Math.atan(f*T/2)*U;f=a/d;c=0.1*ta(c/2)/Math.sqrt(1+f*f);var e=1/1.9,f=[0.1/(c*f),0,0,0,0,0.1/c,0,0,0,0,-2.1*e,-1,0,0,-0.4*e,0],e=m;c=S(e);e=ma(e);c=[c,0,-e,0,0,1,0,0,e,0,c,0,0,0,0,1];var g=-s,e=S(g),g=ma(g);this.mvMatrix=ad(ad(c,[1,0,0,0,0,e,g,0,0,-g,e,0,0,0,0,1]),f)}):delete this.canvas}}function id(a){function b(){if(!da)return null;var a=Lc(q,u);if(!a)return null;
var d=m&&m.src?m.width:Zb,d=d*c(),f=m&&m.src?m.height:Zb,f=f*c();a.x-=d/2;a.y-=f/2;return 0>a.x+d||a.x>e.canvas.width||0>a.y+f||a.y>e.canvas.height?null:new lb(a.x,a.y,d,f)}function d(){if(!C)return null;var a=b();if(!a)return null;e.ctx.save();e.ctx.font=za+"px "+Ja;for(var d=C.split("<br>"),f=0,q=0,f=0;f<d.length;f++){var i=e.ctx.measureText(d[f]);if(i.width>q)q=i.width}e.ctx.restore();a=new lb(a.x+1.2*a.cx,a.y+a.cy/10,q+0.8*za,(f+0.5)*za);d=4*c();if(0>a.x)a.x=0;else if(a.x>e.canvas.width-a.cx*
d)a.x=e.canvas.width-a.cx*d;if(0>a.y)a.y=0;else if(a.y>e.canvas.height-a.cy*d)a.y=e.canvas.height-a.cy*d;return a}function c(){var a=0.2*Math.log(10*k)*i,a=Math.max(a,0.25);return a=Math.min(a,2)}function f(){return h?!0:!1}this.checkTemplate=function(){v||(m=f()?r.imgLink:r.imgInfo);if(!$c)x=r.border;if(!n)s=r.shadow;if(!o)t=r.opacity};this.isUnderCursor=function(){var a=b();return!a?!1:Mb(a)};this.isPopupUnderCursor=function(){var a=d();if(!a)return!1;var b=4*c();a.cx*=b;a.cy*=b;return Mb(a)};this.gotoUrl=
function(){if(h)if("_self"==j)window.location.href=h;else{var a=self.open(h,j);a&&a.focus()}};this.isLink=f;this.paint=function(){var a=b();if(a&&m){e.ctx.globalAlpha=D;try{e.ctx.drawImage(m,a.x,a.y,a.cx,a.cy)}catch(d){}}};this.paintPopup=function(){var a=e.ctx;a.save();a.globalAlpha=D*t;if(s)a.shadowColor="#444",a.shadowBlur=40*c(),a.shadowOffsetX=1,a.shadowOffsetY=1;a.font=za+"px "+Ja;var b=d();if(b){a.strokeStyle=x?"#008":"transparent";a.lineWidth=x?0.5:0;var f=4*c();a.setTransform(f,0,0,f,b.x,
b.y);f=e.ctx.createLinearGradient(0,0,0,b.cy);f.addColorStop(0,"#fff");f.addColorStop(1,"#ccc");a.fillStyle=f;b.x=b.y=0;bd(a,b,2);a.shadowBlur=0;a.shadowOffsetX=0;a.shadowOffsetY=0;a.fillStyle="#008";a.textAlign="left";a.textBaseline="middle";b=C.split("<br>");for(f=0;f<b.length;f++)a.fillText(b[f],0.4*za,za*(f+0.8))}a.restore()};var q=a.pan?Number(a.pan):0,u=a.tilt?Number(a.tilt):0,C=a.text?a.text:null,h=a.url?a.url:null,j=a.target?a.target:"_self",v=!1,$c=!1,n=!1,o=!1;Object.defineProperty(this,
"pan",{set:function(a){q=a;l()},get:function(){return q}});Object.defineProperty(this,"tilt",{set:function(a){u=a;l()},get:function(){return u}});Object.defineProperty(this,"text",{set:function(a){C=a},get:function(){return C}});Object.defineProperty(this,"url",{set:function(a){h=a},get:function(){return h}});Object.defineProperty(this,"target",{set:function(a){j=a},get:function(){return j}});Object.defineProperty(this,"img",{get:function(){return m?m.src:null}});var m;a.img?(m=new Image,m.src=a.img,
v=!0):m=f()?r.imgLink:r.imgInfo;f()&&(C+="  >>");var x=r.border,s=r.shadow,t=r.opacity;if("boolean"==typeof a.border)x=a.border,$c=!0;if("boolean"==typeof a.shadow)s=a.shadow,n=!0;if("number"==typeof a.opacity)t=a.opacity,o=!0;t=M(t,0,1)}function fd(){function a(a){G();c=a;window.removeEventListener("deviceorientation",Xc,!1);window.removeEventListener("compassneedscalibration",Yc,!1);switch(a){case ya:case La:window.addEventListener("deviceorientation",Xc,!1),window.addEventListener("compassneedscalibration",
Yc,!1)}}function b(){switch(c){case ya:return"absolute";case La:return"relative";default:return"none"}}function d(a,b,d){this.pan=a;this.tilt=b;this.timestamp=d}Object.defineProperty(this,"mode",{set:function(b){a(b)},get:function(){return c}});Object.defineProperty(this,"usrMode",{set:function(b){switch(b){case "absolute":a(ya);break;case "relative":a(La);break;default:a(vb)}},get:function(){return b()}});this.setListeners=function(){a(c)};this.newEvent=function(a){var b=0;if(void 0!=window.orientation)b=
window.orientation;else if(void 0!=screen.mozOrientation)switch(screen.mozOrientation){case "landscape-primary":b=90;break;case "portrait-primary":b=0;break;case "landscape-secondary":b=-90;break;case "portrait-secondary":b=180}var e=0,g=0;switch(c){case ya:switch(b){case 90:e=3600-a.alpha+90;$a?e-=a.beta:90<Math.abs(a.beta)&&(e+=180);break;case 0:e=3600-a.alpha-a.gamma;break;case -90:e=3600-a.alpha-90;$a?e+=a.beta:90<Math.abs(a.beta)&&(e+=180);break;case 180:e=3600-a.alpha+a.gamma+180}e%=360;break;
case La:switch(b){case 90:e=-a.beta;break;case 0:e=-a.gamma;break;case -90:e=a.beta;break;case 180:e=a.gamma}}switch(b){case 90:g=-a.gamma-90;90<Math.abs(a.beta)&&(g=$a?-g:0<a.gamma?g+180:90);break;case 0:g=a.beta-90;-90>a.beta&&(g=90);break;case -90:g=a.gamma-90;90<Math.abs(a.beta)&&(g=$a?-g:0>=a.gamma?g+180:90);break;case 180:g=-a.beta-90,90<a.beta&&(g=90)}if(c==ya){b=Date.now();for(a=$a?500:100;0<f.length&&(20<=f.length||f[0].timestamp<=b-a);)f.shift();f.push(new d(e,g,b));this.pan=this.tilt=0;
for(var b=f[f.length-1],g=b.timestamp,b=b.pan,i=0,h=0,k=0,j=f.length-1;0<=j;j--){var m=f[j],l=(a-(g-m.timestamp))/a;if(0>=l)break;var k=k+l,n=m.pan;-180>n-b?n+=360:180<n-b&&(n-=360);e+=360;e%=360;i+=n*l;h+=m.tilt*l}if(k)this.pan=i/k,this.tilt=h/k}else this.pan=e,this.tilt=g};var c=vb,f=[];this.tilt=this.pan=0}function S(a){return a?Math.cos(a*T):1}function ma(a){return Math.sin(a*T)}function ta(a){return Math.tan(a*T)}function Ua(a,b){return Math.atan2(a,b)*U}function ca(a,b){return Math.sqrt(a*a+
b*b)}function M(a,b,d){return a<=b?b:a>=d?d:a}function bd(a,b){a.beginPath();a.rect(b.x,b.y,b.cx,b.cy);a.fill();a.stroke()}function Gb(a,b){this.x=a;this.y=b}function lb(a,b,d,c){this.x=a;this.y=b;this.cx=d;this.cy=c}function vd(a,b){this.pan=a;this.tilt=b;this.yDisp=this.xDisp=0;this.valid=!1}function ud(a,b,d,c,f){this.xSrc=a;this.ySrc=b;this.x=d;this.y=c;this.z=f}function ad(a,b){for(var d=[],c=0,f=0,e,i,h;;){e=0;i=c;for(h=f;!(e+=a[i++]*b[h],h+=4,16<=h););d.push(e);f++;if(4==f){c+=4;if(16==c)break;
f=0}}return d}xc=!1;Wb="2.3.1.24";sb="http://www.panorado.com";uc="(c) 2012-2015 by Karl Maloszek - Simple Software";wc=!1;T=Math.PI/180;U=180/Math.PI;ub=1;A=2;bb=0;Fa=1;qa=2;wa=3;vc=3;fb=3;ga=45;Ha=0.125;Ia=8;Ka=Math.SQRT2;xb=Math.sqrt(Math.sqrt(Math.sqrt(Math.SQRT2)));db=120;eb=81.8;Xb=0.04;Zb=80;za=8;Ja="Arial,sans-serif";Y=30;Ma=20;ab=0;xa=1;Ga=2;cb=3;wb=4;tb=5;vb=0;ya=1;La=2;Yb=void 0;var cd=!1;try{Object.defineProperty(this,"initialized",{get:function(){return cd}})}catch(zd){alert("PanoradoJS requires a browser with ECMAScript 5 support!\nHint: Do not use compatibility mode in MSIE!");
return}this.about=yb;this.reset=ac;this.move=hb;this.moveTo=Hc;this.zoom=Ba;this.zoomToCursor=function(a){J=0;G();ia=!0;O(k*a)};this.setSpeed=H;this.resize=Zc;this.selectImage=cc;this.nextImage=ec;this.setImage=function(a){R=-1;dc(a)};var Ea=navigator.userAgent,dd=navigator.platform,ed=0<=Ea.indexOf("Trident/")||0<=Ea.indexOf("Edge/"),wd=0<=Ea.indexOf("Chrome/")&&0>Ea.indexOf("OPR/"),$a=0<=Ea.indexOf("Firefox/"),xd=0<=Ea.indexOf("OPR/");dd.indexOf("Win32");var Wc=0<=Ea.indexOf("Android");dd.indexOf("iPhone");
var Na="";Object.defineProperty(this,"licenseKey",{set:function(a){Na=a;l()},get:function(){return Na}});var Nc=new Image;Nc.src="";
var gc=640;Object.defineProperty(this,"minLivestreamWidth",{set:function(a){gc=a},get:function(){return gc}});Object.defineProperty(this,"version",{get:function(){return Wb}});Object.defineProperty(this,"info",{get:function(){return zc()}});if("object"!=typeof rb)alert("PanoradoJS object constructor requires a Canvas parameter!");else{Object.defineProperty(this,"canvas",{get:function(){return e.canvas}});var i=window.devicePixelRatio;i||(i=1);var Za=!1;Object.defineProperty(this,"fullWindow",{set:function(a){Sb(a)},
get:function(){return Za}});var nb=!0;Object.defineProperty(this,"fullWindowEnabled",{set:function(a){nb=a?!0:!1},get:function(){return nb}});var ba=null;Object.defineProperty(this,"imageList",{set:function(a){ba=a;R=-1;P.create()},get:function(){return ba}});var R=-1;Object.defineProperty(this,"currentImageId",{set:function(a){cc(a)},get:function(){return R}});var b=null;Object.defineProperty(this,"image",{set:function(a){R=-1;dc(a)},get:function(){return b}});var E=null,hc=!1,Eb=!1,z=ub;Object.defineProperty(this,
"projection",{set:function(a){z="spherical"==a?A:ub;Db();l()},get:function(){return z==A?"spherical":"flat"}});var yd=Ac();Object.defineProperty(this,"isWebGlAvailable",{get:function(){return yd}});Object.defineProperty(this,"useWebGl",{set:function(a){Pc(a)},get:function(){return j?!0:!1}});var Ub=5;Object.defineProperty(this,"gridSize",{set:function(a){Ub=M(a,1,8);Db();l()},get:function(){return Ub}});var ea=!0;Object.defineProperty(this,"enabled",{set:function(a){ea=a?!0:!1},get:function(){return ea}});
var la=Ha,jc=Ha;Object.defineProperty(this,"minScale",{set:function(a){jc=M(a,Ha,Ia);Bb();O(k)},get:function(){return jc}});var Ca=Ia,kc=Ia;Object.defineProperty(this,"maxScale",{set:function(a){kc=M(a,Ha,Ia);Bb();O(k)},get:function(){return kc}});var Z=!1;if(void 0!==document.ontouchstart)try{document.createEvent("TouchEvent"),Z=!0}catch(Ad){}var $=!1;if(navigator.msMaxTouchPoints||navigator.maxTouchPoints)try{document.createEvent("MsPointerEvent"),$=!0}catch(Bd){}Object.defineProperty(this,"isTouchAvailable",
{get:function(){return Z||$}});var aa=Z||$;Object.defineProperty(this,"useTouch",{set:function(a){Rc(a)},get:function(){return aa}});var B=null;try{document.createEvent("DeviceOrientationEvent"),window.addEventListener("deviceorientation",yc,!1),setTimeout(function(){window.removeEventListener("deviceorientation",yc,!1)},2E3)}catch(Cd){}Object.defineProperty(this,"isOrientationAvailable",{get:function(){return B?!0:!1}});Object.defineProperty(this,"orientationMode",{set:function(a){if(B)G(),B.usrMode=
a},get:function(){return B?B.usrMode:"none"}});var na=Z||$;Object.defineProperty(this,"mouseMode",{set:function(a){na="grab"==a;X()},get:function(){return na?"grab":"pan"}});var tc=!1,sc=!1;Object.defineProperty(this,"mouseWheel",{set:function(a){tc="in"==a;sc="ignore"==a},get:function(){return sc?"ignore":tc?"in":"out"}});var Qb="",Pb="",Ob="",Nb="";Object.defineProperty(this,"panCursor0",{set:function(a){ua(a);Qb=a;X()},get:function(){return Qb}});Object.defineProperty(this,"panCursor1",{set:function(a){ua(a);
Pb=a;X()},get:function(){return Pb}});Object.defineProperty(this,"grabCursor0",{set:function(a){ua(a);Ob=a;X()},get:function(){return Ob}});Object.defineProperty(this,"grabCursor1",{set:function(a){ua(a);Nb=a;X()},get:function(){return Nb}});var Ib=2;Object.defineProperty(this,"softPan",{set:function(a){Ib=M(a,0,5)},get:function(){return Ib}});var sa=3;Object.defineProperty(this,"softZoom",{set:function(a){sa=M(a,0,5)},get:function(){return sa}});var lc=0.5;Object.defineProperty(this,"softFade",{set:function(a){lc=
M(a,0,10)},get:function(){return lc}});var y=ab;Object.defineProperty(this,"loaded",{get:function(){return w()}});var Fc=!0,m=0;Object.defineProperty(this,"pan",{set:function(a){w()&&(G(),m=Ra(a),l())},get:function(){return w()?m:0}});var s=0;Object.defineProperty(this,"tilt",{set:function(a){w()&&(G(),s=Sa(a),l())},get:function(){return w()?s:0}});var k=1;Object.defineProperty(this,"scale",{set:function(a){ia=!1;O(a)},get:function(){return k}});var Ta=!1;Object.defineProperty(this,"dispHorzFov",
{get:function(){return w()?Jc():0}});Object.defineProperty(this,"dispVertFov",{get:function(){return w()?Kc():0}});Object.defineProperty(this,"panSpeed",{set:function(a){H(a,null)},get:function(){return w()?n:0}});Object.defineProperty(this,"tiltSpeed",{set:function(a){H(null,a)},get:function(){return w()?o:0}});Object.defineProperty(this,"mousePan",{get:function(){return w()?Da(k,void 0,void 0,void 0,void 0).x:0}});Object.defineProperty(this,"mouseTilt",{get:function(){return w()?Da(k,void 0,void 0,
void 0,void 0).y:0}});Object.defineProperty(this,"videoPlaying",{set:function(a){a?I()&&b.video.play():I()&&b.video.pause()},get:function(){return zb()}});Object.defineProperty(this,"videoSound",{set:function(a){if(I())b.video.muted=!a},get:function(){return Ec()}});Object.defineProperty(this,"videoDuration",{get:function(){return I()&&b.video.duration?b.video.duration:0}});Object.defineProperty(this,"videoCurrentTime",{set:function(a){if(I()){if(0>a)a=0;else if(a>b.video.duration)a=b.video.duration;
b.video.currentTime=a;b.video.play()}},get:function(){return I()&&b.video.currentTime?b.video.currentTime:0}});var Aa=0,D=0,J=0,L=0,n=0,o=0,ha=0,W=0,gb=0,Q=0,ia=!1,pa=0,Uc=0,Vc=0,Qa=null,ob=null,pb=null,Tb=null,Hb=null;Object.defineProperty(this,"onImageLoaded",{set:function(a){Qa=a},get:function(){return Qa}});Object.defineProperty(this,"onClick",{set:function(a){ob=a},get:function(){return ob}});Object.defineProperty(this,"onDblClick",{set:function(a){pb=a},get:function(){return pb}});Object.defineProperty(this,
"onMouseMove",{set:function(a){Tb=a},get:function(){return Tb}});Object.defineProperty(this,"onImageMove",{set:function(a){Hb=a},get:function(){return Hb}});var h=new function(){this.xDown=this.yDown=this.xDown1=this.yDown1=this.xDown2=this.yDown2=this.x=this.y=this.x1=this.y1=this.x2=this.y2=null;this.time=this.startPan=this.startTilt=this.startScale=0;this.clear=function(){this.xDown=this.yDown=this.xDown1=this.yDown1=this.xDown2=this.yDown2=this.x1=this.y1=this.x2=this.y2=null;this.time=this.startPan=
this.startTilt=this.startScale=0};this.clearPinchZoom=function(){this.xDown1=this.yDown1=this.xDown2=this.yDown2=this.x1=this.y1=this.x2=this.y2=null;this.startPan=m;this.startTilt=s;this.startScale=k;this.xDown=this.x;this.yDown=this.y};this.onEvent=function(a){var b=parseInt(e.canvas.style.borderLeftWidth);isNaN(b)&&(b=0);var d=parseInt(e.canvas.style.borderTopWidth);isNaN(d)&&(d=0);for(var c=e.canvas;c;c=c.offsetParent)b+=c.offsetLeft,d+=c.offsetTop;switch(a.type){case "mousedown":this.clear();
this.startPan=m;this.startTilt=s;this.startScale=k;this.x=this.xDown=(a.pageX-b)*i;this.y=this.yDown=(a.pageY-d)*i;break;case "mouseup":case "mouseleave":this.x=(a.pageX-b)*i;this.y=(a.pageY-d)*i;break;case "mousemove":this.x=(a.pageX-b)*i;this.y=(a.pageY-d)*i;break;case "touchstart":this.clear();this.startPan=m;this.startTilt=s;this.startScale=k;if(2>a.touches.length)this.x=this.xDown=(a.changedTouches[0].pageX-b)*i,this.y=this.yDown=(a.changedTouches[0].pageY-d)*i;else if(2==a.touches.length)this.x1=
this.xDown1=(a.touches[0].pageX-b)*i,this.y1=this.yDown1=(a.touches[0].pageY-d)*i,this.x2=this.xDown2=(a.touches[1].pageX-b)*i,this.y2=this.yDown2=(a.touches[1].pageY-d)*i,this.x=this.xDown=(this.x1+this.x2)/2,this.y=this.yDown=(this.y1+this.y2)/2;break;case "touchend":if(1==a.touches.length){this.x=this.xDown=(a.touches[0].pageX-b)*i;this.y=this.yDown=(a.touches[0].pageY-d)*i;this.xDown1=null;break}case "touchmove":if(2>a.touches.length)this.x=(a.changedTouches[0].pageX-b)*i,this.y=(a.changedTouches[0].pageY-
d)*i,this.xDown1=this.yDown1=this.xDown2=this.yDown2=this.x1=this.y1=this.x2=this.y2=null;else if(2==a.touches.length)a.touches[1].target==e.canvas?(this.x1=(a.touches[0].pageX-b)*i,this.y1=(a.touches[0].pageY-d)*i,this.x2=(a.touches[1].pageX-b)*i,this.y2=(a.touches[1].pageY-d)*i,this.x=(this.x1+this.x2)/2,this.y=(this.y1+this.y2)/2):(this.x=(a.changedTouches[0].pageX-b)*i,this.y=(a.changedTouches[0].pageY-d)*i);break;case "pointerdown":a.isPrimary?(this.clear(),this.startPan=m,this.startTilt=s,this.startScale=
k,this.x1=this.xDown1=(a.pageX-b)*i,this.y1=this.yDown1=(a.pageY-d)*i,this.x=this.xDown=this.x1,this.y=this.yDown=this.y1):(this.startPan=m,this.startTilt=s,this.startScale=k,this.x2=this.xDown2=(a.pageX-b)*i,this.y2=this.yDown2=(a.pageY-d)*i,this.x=this.xDown=(this.x1+this.x2)/2,this.y=this.yDown=(this.y1+this.y2)/2);break;case "pointerup":if(this.isPinchZooming()){a.isPrimary?(this.xDown=this.x=this.x2,this.yDown=this.y=this.y2):(this.xDown=this.x=this.x1,this.yDown=this.y=this.y1);this.xDown1=
null;break}case "pointermove":a.isPrimary?(this.x1=(a.pageX-b)*i,this.y1=(a.pageY-d)*i,this.x=null===this.x2?this.x1:(this.x1+this.x2)/2,this.y=null===this.y2?this.y1:(this.y1+this.y2)/2):(this.x2=(a.pageX-b)*i,this.y2=(a.pageY-d)*i,this.x=(this.x1+this.x2)/2,this.y=(this.y1+this.y2)/2)}this.time=mb(a)};this.isDragging=function(){return null!==this.xDown};this.getDragDistX=function(){return null===this.x||null===this.xDown?0:this.x-this.xDown};this.getDragDistY=function(){return null===this.y||null===
this.yDown?0:this.y-this.yDown};this.getDragDist=function(){var a=this.getDragDistX(),b=this.getDragDistY();return ca(a,b)};this.isPinchZooming=function(){return null!==this.xDown1&&null!=this.xDown2};this.getPinchScale=function(){var a=1;if(this.startScale&&null!==this.x1&&null!==this.y1&&null!==this.x2&&null!==this.y2&&null!==this.xDown1&&null!==this.yDown1&&null!==this.xDown2&&null!==this.yDown2){var b=this.x2-this.x1,d=this.y2-this.y1,c=ca(b,d),b=this.xDown2-this.xDown1,d=this.yDown2-this.yDown1,
b=ca(b,d);c/b&&(a=c/b)}return Oa(this.startScale*a)}},Pa=!1;Object.defineProperty(this,"compassVisible",{set:function(a){Pa=a;l()},get:function(){return Pa}});var da=!0;Object.defineProperty(this,"hotspotsVisible",{set:function(a){da=a;l()},get:function(){return da}});var r={imgInfo:Kb(!1),imgLink:Kb(!0),border:!1,shadow:!1,opacity:1};Object.defineProperty(this,"hotspotTemplate",{set:function(a){pd(a)},get:function(){return r}});var N=null,ra=null,e=new function(a){function e(a,b){return a.xDisp>=
b.x&&a.xDisp<=b.x+b.cx&&a.yDisp>=b.y&&a.yDisp<=b.y+b.cy}this.arGrid=this.gridSize=this.dataUrl=this.ctx=this.canvas=null;this.useTriangles=ed;if((this.canvas=a)&&this.canvas.getContext)if(this.ctx=a.getContext("2d")){this.canvas.setAttribute("tabindex",0);this.canvas.setAttribute("hidefocus",!0);a=this.canvas.style;a.outline="none";if(!Number(a.zIndex)||0>a.zIndex)a.zIndex=0;a.position="relative";a.boxSizing="content-box";a["-ms-touch-action"]="none";a["touch-action"]="none";a["-ms-content-zooming"]=
"none";a["content-zooming"]="none";a.background="transparent";this.canvas.addEventListener("keydown",rd);ed&&(this.canvas.addEventListener("MSGestureTap",K),this.canvas.addEventListener("MSGestureHold",K),this.canvas.addEventListener("MSGestureStart",K),this.canvas.addEventListener("MSGestureChange",K),this.canvas.addEventListener("MSGestureEnd",K),this.canvas.addEventListener("MSGestureInertiaStart",K),this.canvas.addEventListener("MSHoldVisual",K));this.canvas.addEventListener("contextmenu",K);
this.canvas.addEventListener("focus",qd);this.canvas.addEventListener("blur",Tc);window.addEventListener("blur",Tc);window.addEventListener("resize",Lb);this.provide2dGrid=function(){this.gridSize=Ub;this.useTriangles||(this.gridSize*=0.5);this.gridSize*=Math.min(4/Math.min(b.width/b.horzFov*k*i,4),2);this.gridSize=b.horzFov/Math.floor(b.horzFov/this.gridSize);var a=Math.round(b.horzFov/this.gridSize);if(b.is360)this.gridSize=b.horzFov/a;var c=Math.round(b.vertFov/this.gridSize);180>b.vertFov&&c++;
a++;c++;if(!this.arGrid||this.arGrid.length!=c)this.arGrid=Array(c);for(var f,e,g=Math.max(-b.vertFov/2-b.horizon,-90),h=Math.min(b.vertFov/2-b.horizon,90),j=0;j<c;j++){if(!this.arGrid[j]||this.arGrid[j].length!=a)this.arGrid[j]=Array(a);e=b.vertFov/2-b.horizon-j*this.gridSize;e>h?e=h:e<g&&(e=g);for(var m=0;m<a;m++)f=m*this.gridSize,this.arGrid[j][m]=new vd(f,e)}};this.update2dGrid=function(a,c,f,e){for(var g=this.arGrid.length,i=this.arGrid[0].length,h=0;h<g;h++)for(var j=0;j<i;j++){var k=this.arGrid[h][j];
k.valid=!1;if(!(k.tilt<f)&&!(k.tilt>e)){if(b.is360&&a>=c){if(k.pan<a&&k.pan>c)continue}else{if(k.pan<a)continue;if(k.pan>c)continue}var m=Lc(k.pan,k.tilt);if(m)k.valid=!0,k.xDisp=m.x,k.yDisp=m.y}}};this.paintFlat=function(a,c,e,g){var h=this.ctx,j=V()?b.video:b.img;h.globalAlpha=D;h.setTransform(1,0,0,1,0,0);var l=b.width,n=b.height,v=m/b.horzFov*l,o=(0.5-(s+b.horizon)/b.vertFov)*n,r=Math.min((e-a)/k/i,l),n=Math.min((g-c)/k/i,n),v=v-r/2,o=o-n/2,r=v+r,n=o+n;0>v&&(b.is360?(v+=l,r+=l):v=0);0>o&&(o=0);
if(wd||xd)v=Math.floor(v),o=Math.floor(o);if(r<=l)h.drawImage(j,v,o,r-v,n-o,a,c,e-a,g-c);else{var w=(l-v)*k*i;$a&&(w=(w+0.5).toFixed(0));h.drawImage(j,v,o,l-v,n-o,a,c,w,g-c);h.drawImage(j,0,o,r-l,n-o,a+w,c,e-a-w,g-c)}};this.paintSpherical=function(a,c,f,h){this.ctx.globalAlpha=D;var a=f-a,j=h-c;this.provide2dGrid();var f=ib(0,0),c=ib(0,j/2),h=ib(a/2,j/2),l=ib(a/2,-j/2),j=ib(0,-j/2);90<Math.abs(c.x-j.x)?0<f.y?(a=b.horzFov/2,f=Math.min(j.y,l.y),h=90):(a=b.horzFov/2,f=-90,h=Math.max(c.y,h.y)):(a=Math.max(h.x,
l.x),f=Math.min(j.y,l.y),h=Math.max(c.y,h.y),a+=this.gridSize);c=-a;a+=m;c+=m;b.is360&&(c=(c+3600)%360,a=(a+3600)%360);-90<f&&(f-=this.gridSize);90>h&&(h+=this.gridSize);this.update2dGrid(c,a,f,h);c=this.arGrid.length-1;h=this.arGrid[0].length-1;a=this.gridSize/b.horzFov*b.width*k*i;f=this.gridSize/b.vertFov*b.height*k*i;a=new lb(-a,-f,this.canvas.width+2*a,this.canvas.height+2*f);for(f=0;f<c;f++)for(l=0;l<h;l++)if(j=this.arGrid[f][l],j.valid){var n=this.arGrid[f][l+1];if(n.valid){var o=this.arGrid[f+
1][l+1];if(o.valid){var v=this.arGrid[f+1][l];if(v.valid&&(e(j,a)||e(n,a)||e(o,a)||e(v,a))){var s=j.pan/b.horzFov*b.width,r=n.pan/b.horzFov*b.width;r==b.width&&r--;this.paintTile(s,(0.5-(j.tilt+b.horizon)/b.vertFov)*b.height,r,(0.5-(v.tilt+b.horizon)/b.vertFov)*b.height,j.xDisp,j.yDisp,n.xDisp,n.yDisp,o.xDisp,o.yDisp,v.xDisp,v.yDisp,0<j.tilt+b.horizon,l<h/2)}}}}};this.paintTile=function(a,b,e,g,h,i,j,k,l,n,m,o,r){this.useTriangles?(this.paintTri(a,b,e,b,e,g,h,i,j,k,l,n,!0),this.paintTri(a,b,e,g,a,
g,h,i,l,n,m,o,!1)):r?this.paintTri(a,b,e,g,a,g,h,i,l,n,m,o,!0):this.paintTri(a,b,e,b,e,g,h,i,j,k,l,n,!1)};this.paintTri=function(a,c,e,g,h,j,l,n,m,o,r,s,w){var x=this.ctx,B=a,t=c,va=e-a,y=j-c,F,e=e-a,g=g-c,h=h-a,j=j-c,a=c=0,m=m-l,o=o-n,r=r-l,s=s-n,fa=h*g-e*j,p=(r*g-m*j)/fa,A=(s*g-o*j)/fa,m=(m*h-r*e)/fa,o=(o*h-s*e)/fa;x.save();x.setTransform(p,A,m,o,l,n);this.useTriangles&&(x.beginPath(),F=1==D?1:0,w?(x.moveTo(a-2*F,c-F),x.lineTo(e+F,g-F),x.lineTo(h+F,j+2*F)):(x.moveTo(a-F,c-2*F),x.lineTo(e+2*F,g+
F),x.lineTo(h-F,j+F)),x.closePath(),x.clip());try{var z=V()?b.video:b.img;F=1==D?10/k/i/this.gridSize:0;va=Math.min(va+F,b.width-B);y=Math.min(y+F,b.height-t);x.drawImage(z,B,t,va,y,0,0,va,y)}catch(E){}x.restore()};this.getInternalBorderRadiusStyle=function(){var a=this.canvas.style,b=a.borderRadius;if(!b||!b.match(/^\d+px$/))return"";a=a.borderWidth;if(!a.match(/^\d+px$/))return"";b=parseInt(b)-parseInt(a);return!b?"":b+"px"}}}(rb),j=new Qc;if(!j.canvas||!j.ctx)j=null;Rc(aa);var P=new function(){function a(){if(e.canvas){t=
[];var a=e.ctx,f=Y*c,i=1.1*Y*c,fa=1.4*Y*c,p=0.9*Y*c;j&&(t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-4,-4);a.lineTo(4,0);a.lineTo(-4,4);a.closePath();a.stroke()},fnClick:function(){ac()}}),p+=fa);m&&I()&&(t.push({x:p,fnPaint:function(){a.lineWidth=1.2;a.beginPath();a.arc(0,0,7,0,2*Math.PI,!0);a.stroke();a.lineWidth=2;zb()?(a.beginPath(),a.moveTo(-2,-3),a.lineTo(-2,3),a.moveTo(2,-3),a.lineTo(2,3),a.stroke()):(a.fillStyle="#fff",a.beginPath(),a.moveTo(-3,-3),a.lineTo(3.5,0),a.lineTo(-3,3),
a.closePath(),a.fill())},fnClick:function(){Dc()}}),p=p+i+f,t.push({x:p,xFactor:3,fnPaint:function(){var c=I()&&b.video.duration?b.video.currentTime/b.video.duration:0;a.fillStyle="rgba(196, 196, 255, 0.6)";a.fillRect(-44,-9,88*c,18);if(I())var c=b.video.currentTime,d=b.video.duration,c=kb(Math.floor(c/60),2)+":"+kb(Math.floor(c%60),2)+" / "+kb(Math.floor(d/60),2)+":"+kb(Math.floor(d%60),2);else c=0;a.font="12px "+Ja;a.textAlign="center";a.textBaseline="alphabetic";a.fillStyle="rgba(255,255,255,1)";
a.fillText(c,0,4)},fnClick:function(){var a=3*Y*c*d(),e=t[g()].x-a/2,a=(h.x-e)/a;if(I()&&b.video.duration)b.video.currentTime=b.video.duration*a,b.video.play()}}),p=p+i+f,t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-7,2);a.lineTo(-4,2);a.lineTo(0,5);a.lineTo(0,-5);a.lineTo(-4,-2);a.lineTo(-7,-2);a.closePath();a.stroke();a.lineWidth=1.2;a.beginPath();a.arc(0,0,4,-0.9,0.9);a.stroke();a.beginPath();a.arc(0,0,7.5,-0.9,0.9);a.stroke();if(Ec())a.lineWidth=1.5,a.moveTo(-8,7),a.lineTo(8,-7),a.moveTo(8,
7),a.lineTo(-8,-7);a.stroke()},fnClick:function(){if(I())b.video.muted=!b.video.muted}}),p+=fa);r&&(t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-4,0);a.lineTo(4,0);a.stroke()},fnClick:function(){Ba(1/Ka)},fnEnabled:function(){return k>la}}),p+=i,t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-4,-1);a.lineTo(0,-4);a.lineTo(0,6);a.stroke()},fnClick:function(){O(1)},fnHilight:function(){return 1==k}}),p+=i,t.push({x:p,fnPaint:function(){a.beginPath();a.strokeRect(-4,-4,8,8)},fnClick:function(){Ta?
Ta=!1:O(0)},fnHilight:function(){return Ta}}),p+=i,t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-4,0);a.lineTo(4,0);a.moveTo(0,-4);a.lineTo(0,4);a.stroke()},fnClick:function(){Ba(Ka)},fnEnabled:function(){return k<Ca}}),p+=fa);s&&(t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(3,-3);a.lineTo(-3,0);a.lineTo(3,3);a.stroke()},fnClick:function(){H(n-2,null)}}),p+=i,t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-3,-4);a.lineTo(-3,4);a.moveTo(3,-4);a.lineTo(3,4);a.stroke()},fnClick:function(){H(0,
0)},fnEnabled:function(){return 0!=n||0!=o}}),p+=i,t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-3,-3);a.lineTo(3,0);a.lineTo(-3,3);a.stroke()},fnClick:function(){H(n+2,null)}}),p+=fa);w&&ba&&1<ba.length&&(t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-3,-3);a.lineTo(-9,0);a.lineTo(-3,3);a.stroke();a.strokeRect(1,-4,8,8)},fnClick:function(){ec(-1)},fnEnabled:function(){return 0<R}}),p+=i,t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(3,-3);a.lineTo(9,0);a.lineTo(3,3);a.stroke();
a.strokeRect(-9,-4,8,8)},fnClick:function(){ec(1)},fnEnabled:function(){return R<ba.length-1}}),p+=fa);v&&N&&N.length&&(t.push({x:p,fnPaint:function(){a.beginPath();a.arc(0,0,4,0,2*Math.PI,!0);a.moveTo(-7,0);a.lineTo(7,0);a.moveTo(0,-7);a.lineTo(0,7);a.stroke()},fnClick:function(){da=!da;l()},fnHilight:function(){return da}}),p+=i);y&&B&&(t.push({x:p,fnPaint:function(){a.lineWidth=1.8;a.beginPath();a.arc(0,0,7,0,2*Math.PI,!0);a.stroke();a.fillStyle="#fff";a.beginPath();a.moveTo(2,2);a.lineTo(-5,5);
a.lineTo(-2,-2);a.lineTo(5,-5);a.closePath();a.arc(0,0,1,0,2*Math.PI,!0);a.fill()},fnClick:function(){if(B)G(),B.usrMode="absolute"==B.usrMode?"none":"absolute"},fnHilight:function(){return"absolute"==B.usrMode}}),p+=i);A&&nb&&(t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-8,2);a.lineTo(-8,6);a.lineTo(-5,6);a.moveTo(8,2);a.lineTo(8,6);a.lineTo(5,6);a.moveTo(-8,-2);a.lineTo(-8,-6);a.lineTo(-5,-6);a.moveTo(8,-2);a.lineTo(8,-6);a.lineTo(5,-6);a.stroke()},fnClick:function(){Sb(!Za)},fnHilight:function(){return Za}}),
p+=i);z&&(t.push({x:p,fnPaint:function(){a.fillStyle=a.strokeStyle;a.font="bold 16px "+Ja;a.textAlign="center";a.textBaseline="alphabetic";a.fillText("?",0,6)},fnClick:function(){G();"javascript:"==z.substr(0,11).toLowerCase()?eval(z.substr(11)):(x=self.open(z,"ViewerHelp","width=500,height=600,location=no,menubar=no,scrollbars=no,resizable=yes,status=no,toolbar=no,titlebar=yes"))&&x.focus()}}),p+=i);D&&(t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(-3,-1);a.lineTo(0,-1);a.lineTo(0,5);a.moveTo(-4,
5);a.lineTo(4,5);a.stroke();a.fillStyle="#fff";a.beginPath();a.arc(-0.5,-5,1.8,0,2*Math.PI,!0);a.fill()},fnClick:function(){yb()}}),p+=i);E&&self.opener&&!e.canvas.oldParentNode&&t.push({x:p,fnPaint:function(){a.beginPath();a.moveTo(0,-7);a.lineTo(0,3);a.stroke();a.beginPath();a.arc(0,1,5,225*Math.PI/180,315*Math.PI/180,!0);a.stroke()},fnClick:function(){x&&!x.closed&&(x.close(),x=null);window.close()}})}}function g(){if(!pc()||!t)return-1;var a=c*d(),b=Y*a/2,f=Ma*a/2,a=e.canvas.height-4*a-f;if(!(h.y>=
a-f&&h.y<=a+f))return-1;for(f=0;f<t.length;f++){var g=t[f],a=g.x*d(),g=b*(g.xFactor?g.xFactor:1);if(h.x>=a-g&&h.x<=a+g)return f}return-1}function d(){return i*(aa?1.25:1)}this.getFunctionUnderCursor=function(){if(!pc()||!t)return null;var a=c*d(),b=Y*a/2,f=Ma*a/2,a=e.canvas.height-4*a-f;if(!(h.y>=a-f&&h.y<=a+f))return null;for(f=0;f<t.length;f++){var a=t[f],g=a.x*d(),i=b*(a.xFactor?a.xFactor:1);if(h.x>=g-i&&h.x<=g+i)return a.fnEnabled?a.fnEnabled()?a.fnClick:!1:a.fnClick}return null};this.mouseOver=
g;this.paint=function(){if(t){var a=e.ctx;a.save();a.globalAlpha=1;a.strokeStyle="#fff";for(var b=c*d(),f=e.canvas.height-4*b-Ma*b/2,g=0;g<t.length;g++){var h=t[g],i=h.x*d(),j=h.xFactor?h.xFactor:1,k=!h.fnEnabled||h.fnEnabled();a.setTransform(b,0,0,b,i,f);a.fillStyle=h.fnHilight&&h.fnHilight()?"rgba(64, 85, 127, 1.0)":"rgba(12, 16, 24, 0.5)";a.lineWidth=0.8;a.strokeStyle=k?"#fff":"#aaa";i=new lb(-Y/2*j,-Ma/2,Y*j,Ma);bd(a,i,3);a.lineWidth=2;h.fnPaint()}a.restore()}};this.create=a;var c=1;Object.defineProperty(this,
"size",{set:function(a){c=M(a,0.7,2);P.create()},get:function(){return c}});var f=!0,j=!0,m=!0,r=!(Z||$),s=!(Z||$),w=!0,v=!0,y=!0,A=!0,z="",D=!0,x=null,E=!0;Object.defineProperty(this,"visible",{set:function(a){f=!!a;l()},get:function(){return f}});Object.defineProperty(this,"reset",{set:function(b){j=!!b;a()},get:function(){return j}});Object.defineProperty(this,"video",{set:function(b){m=!!b;a()},get:function(){return m}});Object.defineProperty(this,"scale",{set:function(b){r=!!b;a()},get:function(){return r}});
Object.defineProperty(this,"motion",{set:function(b){s=!!b;a()},get:function(){return s}});Object.defineProperty(this,"browse",{set:function(b){w=!!b;a()},get:function(){return w}});Object.defineProperty(this,"hotspots",{set:function(b){v=!!b;a()},get:function(){return v}});Object.defineProperty(this,"orientation",{set:function(b){y=!!b;a()},get:function(){return y}});Object.defineProperty(this,"fullWindow",{set:function(b){A=!!b;a()},get:function(){return A}});Object.defineProperty(this,"helpUrl",
{set:function(b){z=b;a()},get:function(){return z}});Object.defineProperty(this,"info",{set:function(b){D=!!b;a()},get:function(){return D}});Object.defineProperty(this,"closeWindow",{set:function(b){E=!!b;a()},get:function(){return E}});var t=null;a()};this.controls=P;var nc=!1,oc=-1;P.create();ua(Qb);ua(Pb);ua(Ob);ua(Nb);Lb();l();setTimeout(function(){try{var a=new Image;a.onload=function(){y=tb;l()};a.onerror=function(){};a.src=sb+"/pjscheck.php?key="+Na+"&ts="+Date.now()}catch(b){}},1E4);cd=!0}}
;
